https://github.com/lukepolson/youtube_channel/blob/main/Python%20Shorts/crossentropy.ipynb

In [1]:
#!pip install SciencePlots

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import scienceplots
plt.style.use(['science', 'notebook'])

In [3]:
p = np.array([5,1,4,6,2,4])
q1 = p
q2 = np.array([3,7,1,4,1,6])
q3 = np.array([2,5,7,2,1,5])

In [6]:
sum(p*np.log(q3))

23.455449144551153

In [7]:
sum(p*np.log(q1))

31.27439562761785

In [8]:
p = np.zeros(10, dtype=int); p[4]=1
q = np.random.rand(10)
q
#q = q/sum(q)

array([0.79363671, 0.0615846 , 0.33323301, 0.83601635, 0.46684133,
       0.81160609, 0.68385696, 0.22993348, 0.0201259 , 0.76703715])

In [9]:
q = q/sum(q)
q

array([0.15860453, 0.01230739, 0.06659504, 0.1670739 , 0.09329602,
       0.16219563, 0.13666557, 0.04595112, 0.00402207, 0.15328874])

In [10]:
p

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [11]:
p>0

array([False, False, False, False,  True, False, False, False, False,
       False])

In [12]:
q[p>0]

array([0.09329602])

In [13]:
H = -np.log(q[p>0])
H

array([2.37197778])

In [14]:
q

array([0.15860453, 0.01230739, 0.06659504, 0.1670739 , 0.09329602,
       0.16219563, 0.13666557, 0.04595112, 0.00402207, 0.15328874])

In [15]:
q[4] = 20
q = q/sum(q) #renormalize
H = -np.log(q[p>0])
H

array([0.0443376])

In [16]:
q

array([7.58630014e-03, 5.88681538e-04, 3.18534362e-03, 7.99140323e-03,
       9.56630946e-01, 7.75806784e-03, 6.53692569e-03, 2.19791298e-03,
       1.92381642e-04, 7.33203739e-03])

In [17]:
p = np.zeros((4,10), dtype=int)
p[0][4] = 1
p[1][2] = 1
p[2][8] = 1
p[3][6] = 1
p

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [19]:
q = np.random.rand(40).reshape(4,10)
q

array([[0.61701684, 0.31675801, 0.04297102, 0.3649951 , 0.88675904,
        0.84032885, 0.63389639, 0.44866355, 0.43659422, 0.43113401],
       [0.25458846, 0.18344899, 0.30879295, 0.50344117, 0.96419848,
        0.31635218, 0.95330438, 0.27325657, 0.01460288, 0.47334123],
       [0.69122725, 0.28059149, 0.29764786, 0.18153875, 0.54589487,
        0.41079178, 0.14934742, 0.78419291, 0.84562839, 0.83871474],
       [0.13604577, 0.96797741, 0.38330872, 0.28525239, 0.36473167,
        0.50156775, 0.95932476, 0.7773654 , 0.78202157, 0.81337339]])

In [20]:
np.sum(q, axis=1)

array([5.01911702, 4.2453273 , 5.02557547, 5.97096882])

In [33]:
np.expand_dims(np.sum(q, axis=1), axis=0)

array([[5.01911702, 4.2453273 , 5.02557547, 5.97096882]])

In [35]:
q = q/np.expand_dims(np.sum(q, axis=1), axis=1)
q

array([[0.12293334, 0.06311031, 0.00856147, 0.07272098, 0.1766763 ,
        0.16742563, 0.1262964 , 0.08939093, 0.08698626, 0.08589838],
       [0.0599691 , 0.04321198, 0.07273714, 0.11858713, 0.22711994,
        0.07451774, 0.2245538 , 0.06436643, 0.00343975, 0.11149699],
       [0.13754191, 0.05583271, 0.05922662, 0.03612298, 0.10862336,
        0.08174025, 0.02971748, 0.15604042, 0.16826499, 0.16688929],
       [0.02278454, 0.16211396, 0.0641954 , 0.04777322, 0.06108417,
        0.08400107, 0.16066484, 0.13019083, 0.13097063, 0.13622134]])

In [36]:
q[p>0]

array([0.1766763 , 0.07273714, 0.16826499, 0.16066484])

In [37]:
Hs = -np.log(q[p>0])
L = sum(Hs)

In [38]:
Hs

array([1.73343602, 2.6209032 , 1.78221524, 1.82843481])

In [39]:
L

7.964989268180718

In [40]:
yhat = 20*np.random.rand(40).reshape(4,10) **2
yhat

array([[ 2.97091375,  0.71792111,  7.51211154,  6.58995319, 15.54903601,
         0.20659475, 15.72631102,  1.79937965, 16.86077809, 15.85241835],
       [ 0.60426605,  0.25660883,  7.27724823, 11.88491176,  1.22356107,
         0.10351819,  0.22925205,  1.22719313,  0.06492981,  2.63893546],
       [ 5.12958647, 19.1618351 ,  9.51968613,  4.49404684,  1.20085563,
         1.00883949,  0.66499721,  6.29082037,  0.352793  ,  0.53973531],
       [ 5.48871119,  3.57721624,  3.97170619, 18.78995734, 12.80340737,
         5.35222146,  0.04131773, 17.57840515, 12.79097073,  0.25358367]])

In [41]:
yhat.shape

(4, 10)

In [43]:
q = np.exp(yhat)
q

array([[1.95097384e+01, 2.05016670e+00, 1.83007374e+03, 7.27746806e+02,
        5.66057483e+06, 1.22948422e+00, 6.75849656e+06, 6.04589575e+00,
        2.10156528e+07, 7.66686494e+06],
       [1.82990866e+00, 1.29253942e+00, 1.44700073e+03, 1.45061310e+05,
        3.39927124e+00, 1.10906597e+00, 1.25765899e+00, 3.41164006e+00,
        1.06708412e+00, 1.39982939e+01],
       [1.68947238e+02, 2.09835637e+08, 1.36253340e+04, 8.94828369e+01,
        3.32295893e+00, 2.74241657e+00, 1.94448510e+00, 5.39595818e+02,
        1.42303654e+00, 1.71555271e+00],
       [2.41945185e+02, 3.57738162e+01, 5.30750096e+01, 1.44668770e+08,
        3.63453763e+05, 2.11076676e+02, 1.04218319e+00, 4.30729243e+07,
        3.58961611e+05, 1.28863520e+00]])

In [44]:
q = q/np.expand_dims(np.sum(q, axis=1), axis=1)
q

array([[4.74641276e-07, 4.98773340e-08, 4.45228180e-05, 1.77049361e-05,
        1.37712890e-01, 2.99114189e-08, 1.64423600e-01, 1.47087142e-07,
        5.11277806e-01, 1.86522775e-01],
       [1.24878030e-05, 8.82064667e-06, 9.87473337e-03, 9.89938517e-01,
        2.31975675e-05, 7.56857303e-06, 8.58261293e-06, 2.32819758e-05,
        7.28207729e-06, 9.55282309e-05],
       [8.05085447e-07, 9.99931215e-01, 6.49288985e-05, 4.26413184e-07,
        1.58349193e-08, 1.30684567e-08, 9.26606834e-09, 2.57133970e-06,
        6.78120592e-09, 8.17513523e-09],
       [1.28376956e-06, 1.89817111e-07, 2.81617844e-07, 7.67617519e-01,
        1.92849829e-03, 1.11998017e-06, 5.52986018e-09, 2.28546432e-01,
        1.90466277e-03, 6.83754310e-09]])

In [45]:
q.shape

(4, 10)

In [46]:
q.sum(axis=1)

array([1., 1., 1., 1.])

In [47]:
p

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [48]:
c_squig = np.where(p)
c_squig

(array([0, 1, 2, 3]), array([4, 2, 8, 6]))

In [49]:
q[c_squig]

array([1.37712890e-01, 9.87473337e-03, 6.78120592e-09, 5.52986018e-09])

In [50]:
Hs = -np.log(q[c_squig])
L = sum(Hs)

In [51]:
Hs

array([ 1.98258427,  4.61777597, 18.80911089, 19.01310331])

In [52]:
L

44.4225744293559

In [53]:
L = torch.nn.CrossEntropyLoss(reduction='sum')

In [54]:
yhat

array([[ 2.97091375,  0.71792111,  7.51211154,  6.58995319, 15.54903601,
         0.20659475, 15.72631102,  1.79937965, 16.86077809, 15.85241835],
       [ 0.60426605,  0.25660883,  7.27724823, 11.88491176,  1.22356107,
         0.10351819,  0.22925205,  1.22719313,  0.06492981,  2.63893546],
       [ 5.12958647, 19.1618351 ,  9.51968613,  4.49404684,  1.20085563,
         1.00883949,  0.66499721,  6.29082037,  0.352793  ,  0.53973531],
       [ 5.48871119,  3.57721624,  3.97170619, 18.78995734, 12.80340737,
         5.35222146,  0.04131773, 17.57840515, 12.79097073,  0.25358367]])

In [55]:
p

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [57]:
loss = L(torch.tensor(yhat), torch.tensor(p, dtype=torch.float))
loss

tensor(44.4226, dtype=torch.float64)